/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp;

import com.sun.javafx.scene.layout.region.Margins;
import dao.DaoMotorista;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Motorista;


public class VisaoMotorista extends javax.swing.JPanel {

    /**
     * Creates new form Motorista
     */
    public VisaoMotorista() {
        initComponents();
    }
    
    Motorista m = new Motorista ();
    DaoMotorista daoMotorista = new DaoMotorista();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param args
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotoesSexo = new javax.swing.ButtonGroup();
        tituloNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        tituloCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        radioButtonFeminino = new javax.swing.JRadioButton();
        radioButtomMasculino = new javax.swing.JRadioButton();
        tituloSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        tituloTipoMotorista = new javax.swing.JLabel();
        txtTipoMotorista = new javax.swing.JTextField();
        painelDepartamento = new javax.swing.JPanel();
        tituloNomeDepartamento = new javax.swing.JLabel();
        txtNomeDepartamento = new javax.swing.JTextField();
        tituloRuaDepartamento = new javax.swing.JLabel();
        txtRuaDepartamento = new javax.swing.JTextField();
        tituloBairroDepartamento = new javax.swing.JLabel();
        txtBairroDepartamento = new javax.swing.JTextField();
        tituloNumeroDepartamento = new javax.swing.JLabel();
        txtNumeroDepartamento = new javax.swing.JTextField();
        tituloComplementoDepartamento = new javax.swing.JLabel();
        txtComplementoDepartamento = new javax.swing.JTextField();
        tituloCidadeDepartamento = new javax.swing.JLabel();
        tituloEstadoDepartamento = new javax.swing.JLabel();
        tituloCepDepartamento = new javax.swing.JLabel();
        txtCidadeDepartamento = new javax.swing.JTextField();
        txtEstadoDepartamento = new javax.swing.JTextField();
        txtCepDepartamento = new javax.swing.JTextField();
        painelTelefone = new javax.swing.JPanel();
        tituloTelefoneFixo = new javax.swing.JLabel();
        txtTelefoneFixo = new javax.swing.JTextField();
        tituloTelefoneCelular = new javax.swing.JLabel();
        txtTelefoneCelular = new javax.swing.JTextField();
        comboBoxBeneficio = new javax.swing.JComboBox();
        painelEnderecoMotorista = new javax.swing.JPanel();
        tituloRuaMotorista = new javax.swing.JLabel();
        txtRuaMotorista = new javax.swing.JTextField();
        tituloBairroMotorista = new javax.swing.JLabel();
        txtBairroMotorista = new javax.swing.JTextField();
        tituloNumeroMotorista = new javax.swing.JLabel();
        txtNumeroMotorista = new javax.swing.JTextField();
        tituloComplementoMotorista = new javax.swing.JLabel();
        txtComplementoMotorista = new javax.swing.JTextField();
        tituloCidadeMotorista = new javax.swing.JLabel();
        txtCidadeMotorista = new javax.swing.JTextField();
        tituloEstadoMotorista = new javax.swing.JLabel();
        txtEstadoMotorista = new javax.swing.JTextField();
        tituloCepMotorista = new javax.swing.JLabel();
        txtCepMotorista = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        botaoInserir = new javax.swing.JToggleButton();
        botaoConsultar = new javax.swing.JToggleButton();
        tituloCodigo = new javax.swing.JLabel();
        txtCodigoMotorista = new javax.swing.JTextField();

        tituloNome.setText("Nome:");

        tituloCPF.setText("Cpf:");

        GrupoBotoesSexo.add(radioButtonFeminino);
        radioButtonFeminino.setText("Feminino");
        radioButtonFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonFemininoActionPerformed(evt);
            }
        });

        GrupoBotoesSexo.add(radioButtomMasculino);
        radioButtomMasculino.setText("Masculino");
        radioButtomMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtomMasculinoActionPerformed(evt);
            }
        });

        tituloSalario.setText("Salário:");

        tituloTipoMotorista.setText("Tipo:");

        txtTipoMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoMotoristaActionPerformed(evt);
            }
        });

        painelDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Departamento:"));

        tituloNomeDepartamento.setText("Nome:");

        tituloRuaDepartamento.setText("Rua:");

        tituloBairroDepartamento.setText("Bairro:");

        tituloNumeroDepartamento.setText("Número:");

        txtNumeroDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDepartamentoActionPerformed(evt);
            }
        });

        tituloComplementoDepartamento.setText("Complemento:");

        tituloCidadeDepartamento.setText("Cidade:");

        tituloEstadoDepartamento.setText("Estado:");

        tituloCepDepartamento.setText("Cep:");

        javax.swing.GroupLayout painelDepartamentoLayout = new javax.swing.GroupLayout(painelDepartamento);
        painelDepartamento.setLayout(painelDepartamentoLayout);
        painelDepartamentoLayout.setHorizontalGroup(
            painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDepartamentoLayout.createSequentialGroup()
                .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairroDepartamento)
                    .addGroup(painelDepartamentoLayout.createSequentialGroup()
                        .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDepartamentoLayout.createSequentialGroup()
                                .addComponent(txtNumeroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(tituloComplementoDepartamento))
                            .addComponent(tituloBairroDepartamento)
                            .addComponent(tituloNomeDepartamento)
                            .addComponent(tituloRuaDepartamento)
                            .addComponent(txtRuaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloNumeroDepartamento)
                            .addComponent(tituloCidadeDepartamento))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDepartamentoLayout.createSequentialGroup()
                        .addComponent(txtCidadeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDepartamentoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCepDepartamento))
                            .addGroup(painelDepartamentoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDepartamentoLayout.createSequentialGroup()
                                        .addComponent(tituloEstadoDepartamento)
                                        .addGap(56, 56, 56)
                                        .addComponent(tituloCepDepartamento))
                                    .addComponent(txtComplementoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstadoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        painelDepartamentoLayout.setVerticalGroup(
            painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDepartamentoLayout.createSequentialGroup()
                .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelDepartamentoLayout.createSequentialGroup()
                        .addComponent(tituloNomeDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloRuaDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRuaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloBairroDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloNumeroDepartamento)
                            .addComponent(tituloComplementoDepartamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplementoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNumeroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCidadeDepartamento)
                    .addComponent(tituloEstadoDepartamento)
                    .addComponent(tituloCepDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCepDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        painelTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone:"));

        tituloTelefoneFixo.setText("Fixo:");

        tituloTelefoneCelular.setText("Celular:");

        javax.swing.GroupLayout painelTelefoneLayout = new javax.swing.GroupLayout(painelTelefone);
        painelTelefone.setLayout(painelTelefoneLayout);
        painelTelefoneLayout.setHorizontalGroup(
            painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelefoneLayout.createSequentialGroup()
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTelefoneFixo)
                    .addComponent(txtTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTelefoneCelular)))
        );
        painelTelefoneLayout.setVerticalGroup(
            painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefoneLayout.createSequentialGroup()
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTelefoneFixo)
                    .addComponent(tituloTelefoneCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        comboBoxBeneficio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBeneficioActionPerformed(evt);
            }
        });

        painelEnderecoMotorista.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço:"));

        tituloRuaMotorista.setText("Rua:");

        tituloBairroMotorista.setText("Bairro:");

        tituloNumeroMotorista.setText("Número:");

        tituloComplementoMotorista.setText("Complemento:");

        tituloCidadeMotorista.setText("Cidade:");

        tituloEstadoMotorista.setText("Estado:");

        tituloCepMotorista.setText("Cep:");

        javax.swing.GroupLayout painelEnderecoMotoristaLayout = new javax.swing.GroupLayout(painelEnderecoMotorista);
        painelEnderecoMotorista.setLayout(painelEnderecoMotoristaLayout);
        painelEnderecoMotoristaLayout.setHorizontalGroup(
            painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoMotoristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloRuaMotorista)
                    .addComponent(tituloBairroMotorista)
                    .addComponent(txtRuaMotorista)
                    .addComponent(txtBairroMotorista)
                    .addGroup(painelEnderecoMotoristaLayout.createSequentialGroup()
                        .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloNumeroMotorista)
                            .addComponent(txtNumeroMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCidadeMotorista))
                        .addGap(25, 25, 25)
                        .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoMotorista)
                            .addGroup(painelEnderecoMotoristaLayout.createSequentialGroup()
                                .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloComplementoMotorista)
                                    .addGroup(painelEnderecoMotoristaLayout.createSequentialGroup()
                                        .addComponent(tituloEstadoMotorista)
                                        .addGap(33, 33, 33)
                                        .addComponent(tituloCepMotorista)))
                                .addGap(0, 123, Short.MAX_VALUE))))
                    .addGroup(painelEnderecoMotoristaLayout.createSequentialGroup()
                        .addComponent(txtCidadeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCepMotorista)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEnderecoMotoristaLayout.setVerticalGroup(
            painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoMotoristaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloRuaMotorista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRuaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloBairroMotorista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairroMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNumeroMotorista)
                    .addComponent(tituloComplementoMotorista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplementoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCidadeMotorista)
                    .addComponent(tituloEstadoMotorista)
                    .addComponent(tituloCepMotorista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        painelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Botões:"));

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        botaoConsultar.setText("Consultar");

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botaoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(botaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserir)
                    .addComponent(botaoConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tituloCodigo.setText("Código:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(tituloNome)
                    .addComponent(tituloCPF)
                    .addComponent(tituloSalario)
                    .addComponent(tituloTipoMotorista)
                    .addComponent(txtCPF)
                    .addComponent(txtSalario)
                    .addComponent(txtNome)
                    .addComponent(painelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(radioButtonFeminino)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButtomMasculino))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtTipoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(comboBoxBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tituloCodigo)
                    .addComponent(txtCodigoMotorista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelEnderecoMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelEnderecoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(tituloSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonFeminino)
                            .addComponent(radioButtomMasculino))
                        .addGap(18, 18, 18)
                        .addComponent(tituloTipoMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(painelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonFemininoActionPerformed

    private void txtNumeroDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDepartamentoActionPerformed

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed

        try {
            // Pegar dados
            String cpf = txtCPF.getText();

            // Verificar se o CPF contém apenas números
            if (!cpf.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Digite apenas números no campo CPF");
                return;
            }

            // Verificar se o CPF possui 11 dígitos
            if (cpf.length() != 11) {
                JOptionPane.showMessageDialog(null, "CPF deve conter 11 caracteres numéricos");
                return;
            }
            m.setCpf(cpf);
            m.setCodigo(Integer.parseInt(txtCodigoMotorista.getText()));
            m.setNome(txtNome.getText());
            m.setSalario(Float.parseFloat(txtSalario.getText()));
            m.setTipo_motorista(txtTipoMotorista.getText());

            // Verificar o sexo
            String sexo = "";
            if (radioButtonFeminino.isSelected()) {
                sexo = "Feminino";
            } else if (radioButtomMasculino.isSelected()) {
                sexo = "Masculino";
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o sexo");
                return;
            }
            m.setSexo(sexo);


            // Inserir
            daoMotorista.InserirMotorista(m);
            JOptionPane.showMessageDialog(null, "Motorista salvo com sucesso");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Certifique-se de preencher todos os campos corretamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Motorista não foi salvo com sucesso");
        }
    }//GEN-LAST:event_botaoInserirActionPerformed

    private void comboBoxBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBeneficioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxBeneficioActionPerformed

    private void txtTipoMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoMotoristaActionPerformed

    private void radioButtomMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtomMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtomMasculinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotoesSexo;
    private javax.swing.JToggleButton botaoConsultar;
    private javax.swing.JToggleButton botaoInserir;
    private javax.swing.JComboBox comboBoxBeneficio;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDepartamento;
    private javax.swing.JPanel painelEnderecoMotorista;
    private javax.swing.JPanel painelTelefone;
    private javax.swing.JRadioButton radioButtomMasculino;
    private javax.swing.JRadioButton radioButtonFeminino;
    private javax.swing.JLabel tituloBairroDepartamento;
    private javax.swing.JLabel tituloBairroMotorista;
    private javax.swing.JLabel tituloCPF;
    private javax.swing.JLabel tituloCepDepartamento;
    private javax.swing.JLabel tituloCepMotorista;
    private javax.swing.JLabel tituloCidadeDepartamento;
    private javax.swing.JLabel tituloCidadeMotorista;
    private javax.swing.JLabel tituloCodigo;
    private javax.swing.JLabel tituloComplementoDepartamento;
    private javax.swing.JLabel tituloComplementoMotorista;
    private javax.swing.JLabel tituloEstadoDepartamento;
    private javax.swing.JLabel tituloEstadoMotorista;
    private javax.swing.JLabel tituloNome;
    private javax.swing.JLabel tituloNomeDepartamento;
    private javax.swing.JLabel tituloNumeroDepartamento;
    private javax.swing.JLabel tituloNumeroMotorista;
    private javax.swing.JLabel tituloRuaDepartamento;
    private javax.swing.JLabel tituloRuaMotorista;
    private javax.swing.JLabel tituloSalario;
    private javax.swing.JLabel tituloTelefoneCelular;
    private javax.swing.JLabel tituloTelefoneFixo;
    private javax.swing.JLabel tituloTipoMotorista;
    private javax.swing.JTextField txtBairroDepartamento;
    private javax.swing.JTextField txtBairroMotorista;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCepDepartamento;
    private javax.swing.JTextField txtCepMotorista;
    private javax.swing.JTextField txtCidadeDepartamento;
    private javax.swing.JTextField txtCidadeMotorista;
    private javax.swing.JTextField txtCodigoMotorista;
    private javax.swing.JTextField txtComplementoDepartamento;
    private javax.swing.JTextField txtComplementoMotorista;
    private javax.swing.JTextField txtEstadoDepartamento;
    private javax.swing.JTextField txtEstadoMotorista;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeDepartamento;
    private javax.swing.JTextField txtNumeroDepartamento;
    private javax.swing.JTextField txtNumeroMotorista;
    private javax.swing.JTextField txtRuaDepartamento;
    private javax.swing.JTextField txtRuaMotorista;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefoneCelular;
    private javax.swing.JTextField txtTelefoneFixo;
    private javax.swing.JTextField txtTipoMotorista;
    // End of variables declaration//GEN-END:variables

    void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
