/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp;

import modelo.Departamento;

/**
 *
 * @author Amanda
 */
public class VisaoDepartamento extends javax.swing.JPanel {

    /**
     * Creates new form VisaoDepartamento
     */
    public VisaoDepartamento() {
        initComponents();
    }
    
    Departamento d = new Departamento ();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloNomeDepartamento = new javax.swing.JLabel();
        txtNomeDepartamento = new javax.swing.JTextField();
        painelEnderecoDepartamento = new javax.swing.JPanel();
        tituloRuaDepartamento = new javax.swing.JLabel();
        txtRuaDepartamento = new javax.swing.JTextField();
        tituloBairroDepartamento = new javax.swing.JLabel();
        txtBairroDepartamento = new javax.swing.JTextField();
        tituloNumeroDepartamento = new javax.swing.JLabel();
        txtNumeroDepartamento = new javax.swing.JTextField();
        tituloComplementoMotorista = new javax.swing.JLabel();
        txtComplementoDepartamento = new javax.swing.JTextField();
        tituloCidadeDepartamento = new javax.swing.JLabel();
        txtCidadeDepartamento = new javax.swing.JTextField();
        tituloEstadoDepartamento = new javax.swing.JLabel();
        txtEstadoDepartamento = new javax.swing.JTextField();
        tituloCepDepartamento = new javax.swing.JLabel();
        txtCepDepartamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtConsultaDepartamento = new javax.swing.JTextField();
        botaoConsultaDepartamento = new javax.swing.JButton();
        botaoExcluirDepartamento = new javax.swing.JButton();
        botaoInserirDepartamento = new javax.swing.JButton();
        botaoAtualizarDepartamento = new javax.swing.JButton();

        tituloNomeDepartamento.setText("Nome:");

        painelEnderecoDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço:"));

        tituloRuaDepartamento.setText("Rua:");

        tituloBairroDepartamento.setText("Bairro:");

        tituloNumeroDepartamento.setText("Número:");

        tituloComplementoMotorista.setText("Complemento:");

        tituloCidadeDepartamento.setText("Cidade:");

        tituloEstadoDepartamento.setText("Estado:");

        tituloCepDepartamento.setText("Cep:");

        javax.swing.GroupLayout painelEnderecoDepartamentoLayout = new javax.swing.GroupLayout(painelEnderecoDepartamento);
        painelEnderecoDepartamento.setLayout(painelEnderecoDepartamentoLayout);
        painelEnderecoDepartamentoLayout.setHorizontalGroup(
            painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloRuaDepartamento)
                    .addComponent(tituloBairroDepartamento)
                    .addComponent(txtRuaDepartamento)
                    .addComponent(txtBairroDepartamento)
                    .addGroup(painelEnderecoDepartamentoLayout.createSequentialGroup()
                        .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloNumeroDepartamento)
                            .addComponent(txtNumeroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCidadeDepartamento))
                        .addGap(25, 25, 25)
                        .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoDepartamento)
                            .addGroup(painelEnderecoDepartamentoLayout.createSequentialGroup()
                                .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloComplementoMotorista)
                                    .addGroup(painelEnderecoDepartamentoLayout.createSequentialGroup()
                                        .addComponent(tituloEstadoDepartamento)
                                        .addGap(33, 33, 33)
                                        .addComponent(tituloCepDepartamento)))
                                .addGap(0, 123, Short.MAX_VALUE))))
                    .addGroup(painelEnderecoDepartamentoLayout.createSequentialGroup()
                        .addComponent(txtCidadeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCepDepartamento)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        painelEnderecoDepartamentoLayout.setVerticalGroup(
            painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloRuaDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRuaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloBairroDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNumeroDepartamento)
                    .addComponent(tituloComplementoMotorista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplementoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCidadeDepartamento)
                    .addComponent(tituloEstadoDepartamento)
                    .addComponent(tituloCepDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        botaoConsultaDepartamento.setText("Consultar");

        botaoExcluirDepartamento.setText("Excluir");

        botaoInserirDepartamento.setText("Inserir");

        botaoAtualizarDepartamento.setText("Atualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(painelEnderecoDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloNomeDepartamento)
                        .addComponent(txtNomeDepartamento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoExcluirDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAtualizarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtConsultaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoConsultaDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(botaoInserirDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloNomeDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelEnderecoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(botaoInserirDepartamento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultaDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botaoExcluirDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoAtualizarDepartamento)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarDepartamento;
    private javax.swing.JButton botaoConsultaDepartamento;
    private javax.swing.JButton botaoExcluirDepartamento;
    private javax.swing.JButton botaoInserirDepartamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel painelEnderecoDepartamento;
    private javax.swing.JLabel tituloBairroDepartamento;
    private javax.swing.JLabel tituloCepDepartamento;
    private javax.swing.JLabel tituloCidadeDepartamento;
    private javax.swing.JLabel tituloComplementoMotorista;
    private javax.swing.JLabel tituloEstadoDepartamento;
    private javax.swing.JLabel tituloNomeDepartamento;
    private javax.swing.JLabel tituloNumeroDepartamento;
    private javax.swing.JLabel tituloRuaDepartamento;
    private javax.swing.JTextField txtBairroDepartamento;
    private javax.swing.JTextField txtCepDepartamento;
    private javax.swing.JTextField txtCidadeDepartamento;
    private javax.swing.JTextField txtComplementoDepartamento;
    private javax.swing.JTextField txtConsultaDepartamento;
    private javax.swing.JTextField txtEstadoDepartamento;
    private javax.swing.JTextField txtNomeDepartamento;
    private javax.swing.JTextField txtNumeroDepartamento;
    private javax.swing.JTextField txtRuaDepartamento;
    // End of variables declaration//GEN-END:variables
}
